### ISSUE TITLE
Notification: To provide you with the best experience in Asana, please update your browser.

### ISSUE THREAD

**Issue by sanderbaas** [madhur/snap-asana#1]
Since last week I receive the notification below in asana-snap
`To provide you with the best experience in Asana, please update your browser.`

I don't know anything about Electron, but would it help to bump the version of electron?

**Comment by madhur** [comment]
Thanks for bringing this to notice @sanderbaas . I have bumped the version of electron and released the new version. The notification seems to be gone.

**Comment by sanderbaas** [comment]
Thanks a lot! The issue seems to be fixed here as well.
